name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: mskelton/setup-yarn@37d1b9a20fd320c216fff7d4e6eea6f85c95a892 # v1
        with:
          node-version: "18.x"

      - name: Run ESLint
        run: yarn lint